api = "0.6"

[buildpack]
id = "heroku/nodejs-function-invoker"
version = "0.1.0"
name = "Node.js Function Invoker"
clear-env = true
homepage = "https://github.com/heroku/buildpacks-nodejs"
keywords = ["nodejs", "node", "javascript", "function"]

[[licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]

[metadata.runtime]
# TODO: Replace this with the actual invoker runtime archive URL.
# This is currently using a random .tar.gz URL to test download/extraction.
url = "https://nodejs.org/download/release/latest-v14.x/node-v14.16.1-linux-x64.tar.gz"

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-nodejs-function-invoker-buildpack"
